# Generated by Django 4.2.5 on 2024-01-31 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('archivo_video', models.FileField(upload_to='videos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
