# Generated by Django 4.2.5 on 2024-01-31 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
