# Generated by Django 4.2.5 on 2024-02-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0003_delete_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguidor',
        ),
    ]
